name: wishlist Build And Push

on:

  push:
    branches:
      - main

  workflow_dispatch:

jobs:


  pre-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.11"

      - name: Verify Python
        run: python --version

      - name: Install Dependencies
        run: |
            pip install -r requirements.txt

      - name: Validate Python Syntax
        run: |
            python -m py_compile index.py

      - name: Verify Imports
        run: |
            python -c "from flask import Flask"
            python -c "from flask_cors import CORS"


  build-and-push:
        
    needs: pre-build

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Verify AWS Login
        run: aws sts get-caller-identity

      - name: Login To Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker Version
        run: docker --version

      - name: Build WISHLIST Image
        run: |
          docker build \
          -t 663566123253.dkr.ecr.ap-south-2.amazonaws.com/wishlist:${{ github.run_number }} \
          .

      - name: Push WISHLIST Image
        run: |
          docker push \
          663566123253.dkr.ecr.ap-south-2.amazonaws.com/wishlist:${{ github.run_number }}


  deploy:

    needs: build-and-push

    runs-on: ubuntu-latest

    steps:

      - name: Deploy WISHLIST To EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |

            cd ~/devops_wishlist

            git pull origin main

            sed -i "s/^WISHLIST_TAG=.*/WISHLIST_TAG=${{ github.run_number }}/" .env

            echo "===== UPDATED ENV ====="
            cat .env

            aws ecr get-login-password \
            --region ap-south-2 \
            | docker login \
            --username AWS \
            --password-stdin \
            663566123253.dkr.ecr.ap-south-2.amazonaws.com

            docker network inspect micro-net >/dev/null 2>&1 || \
            docker network create micro-net

            docker compose pull wishlist

            docker compose up -d --force-recreate wishlist

            docker ps

  notify:

    if: always()

    needs:
      - pre-build
      - build-and-push
      - deploy

    runs-on: ubuntu-latest

    steps:

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-2

      - name: Send SNS Notification

        run: |

          STATUS="${{ needs.deploy.result }}"
          BUILD_STATUS="${{ needs.pre-build.result }}"
          PUSH_STATUS="${{ needs.build-and-push.result }}"
          DEPLOY_STATUS="${{ needs.deploy.result }}"
          if [ "$BUILD_STATUS" != "success" ]; then
            FAILURE_POINT="Pre-Build"
          elif [ "$PUSH_STATUS" != "success" ]; then
            FAILURE_POINT="Build-And-Push"
          elif [ "$DEPLOY_STATUS" != "success" ]; then
            FAILURE_POINT="Deploy"
          else
            FAILURE_POINT="None"
          fi

          if [ "$BUILD_STATUS" = "success" ] && \
            [ "$PUSH_STATUS" = "success" ] && \
            [ "$DEPLOY_STATUS" = "success" ]; then

            OVERALL_STATUS="SUCCESS"

          else

            OVERALL_STATUS="FAILURE"

          fi

          aws sns publish \
          --region ap-south-2 \
          --topic-arn "${{ secrets.SNS_TOPIC_ARN }}" \
          --subject "WISHLIST Deployment ${OVERALL_STATUS}" \
          --message "
          Repository      : devops_WISHLIST

          Build Number    : ${{ github.run_number }}

          Overall Status  : ${OVERALL_STATUS}

          Pre-Build       : ${BUILD_STATUS}

          Build-And-Push  : ${PUSH_STATUS}

          Deploy          : ${DEPLOY_STATUS}

          Failure Point   : ${FAILURE_POINT}

          Commit          : ${{ github.sha }}

          Workflow        : ${{ github.workflow }}

          Repository URL  :
          https://github.com/${{ github.repository }}

          Run URL :
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          "